name: Build image on Tag
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker
        uses: docker/build-push-action@v1
        with:
          path: docker
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pgk.github.com
          repository: mpapenbr/ghtest/mytest
          tag_with_ref: true
